; Jump Table from 2892 to 2957 (99 entries, indexed by _RAM_CF80_)
entityTypeJumpTable:
.dw updateAlex
.dw updateEntity0x02
.dw updateEntity0x03
.dw updateEntity0x04
.dw updateEntity0x05
.dw updateEntity0x06
.dw updateEntity0x07
.dw updateEntity0x08
.dw updateEntity0x09
.dw updateEntity0x0A
.dw updateEntity0x0B
.dw updateEntity0x0C
.dw updateGoosekaHead
.dw updateChokkinnaHead
.dw updateParplinHead
.dw updateEntity0x10
.dw updateEntity0x11
.dw updateEntity0x12
.dw updateEntity0x13
.dw updateEntity0x14
.dw updateEntity0x15
.dw updateEntity0x16
.dw updateEntity0x17
.dw return
.dw updateEntity0x19
.dw updateEntity0x1A
.dw updateEntity0x1B
.dw updateJanken
.dw updateGooseka
.dw updateChokkinna
.dw updateParplin
.dw updateBatLeft
.dw updateEntity0x21
.dw updateMermanBubbles
.dw updateMerman
.dw updateOctopusArm
.dw updateEntity0x25
.dw updateEntity0x26
.dw updateEntity0x27
.dw updateEntity0x28
.dw updateEntity0x29
.dw updateEntity0x2A
.dw updateSmokePuff
.dw updatePlant
.dw updateMonsterbirdLeft
.dw updateKillerFishLeft
.dw updateEntity0x2F
.dw updateSmallFishLeft
.dw updateSeaHorseLeft
.dw updateSeaHorseRight
.dw updateMonsterbirdRight
.dw updateSmallFishRight
.dw updateKillerFishRight
.dw updateBatRight
.dw updateMonsterFrogJumping
.dw updateDebrisTopLeft
.dw updateEntity0x39
.dw updateEntity0x3A
.dw updateEntity0x3B
.dw updateMoneyBag
.dw updateEntity0x3D
.dw updateflameOrScorpionLeft
.dw updateflameOrScorpionRight
.dw updateEntity0x40
.dw updateEntity0x41
.dw updateEntity0x42
.dw updateEntity0x43
.dw updateRiceBall
.dw updateSaintNurari
.dw updateEntity0x46
.dw updateEntity0x47
.dw updateEntity0x48
.dw updateEntity0x49
.dw updateEntity0x4A
.dw updateNametableChanger
.dw updateEntity0x4C
.dw updateEntity0x4D
.dw updatePowerBracelet
.dw updateGhost
.dw updateEntity0x50
.dw updateEntity0x51
.dw updateEntity0x52
.dw updateEntity0x53
.dw updateEntity0x54
.dw updateEntity0x55
.dw updateArrow
.dw updateEntity0x57
.dw updateJankensCastle
.dw $0000
.dw $0000
.dw $0000
.dw $0000
.dw $0000
.dw $0000
.dw $0000
.dw updateEntity0x60
.dw updateEntity0x61
.dw updateEntity0x62
.dw updateEntity0x63
