ENTITY_ARRAY_SIZE = $1E

; Entity types
ENTITY_ALEX                     = $01
ENTITY_GOOSEKA_HEAD             = $0D
ENTITY_CHOKKINNA_HEAD           = $0E
ENTITY_PARPLIN_HEAD             = $0F
ENTITY_STATIC                   = $18
ENTITY_CHOKKINNA_SPELL          = $1A
ENTITY_JANKEN                   = $1C
ENTITY_GOOSEKA                  = $1D
ENTITY_CHOKKINNA                = $1E
ENTITY_PARPLIN                  = $1F
ENTITY_BAT_LEFT                 = $20
ENTITY_ITEM_SELECT_ARROW        = $21
ENTITY_MERMAN_BUBBLE            = $22
ENTITY_MERMAN                   = $23
ENTITY_OCTOPUS_ARM              = $24
ENTITY_MONKEY_LEAF              = $29
ENTITY_SMOKE_PUFF               = $2B
ENTITY_PLANT                    = $2C
ENTITY_MONSTERBIRD_LEFT         = $2D
ENTITY_KILLER_FISH_LEFT         = $2E
ENTITY_MONSTER_FROG             = $2F
ENTITY_SMALL_FISH_LEFT          = $30
ENTITY_SEA_HORSE_LEFT           = $31
ENTITY_SEA_HORSE_RIGHT          = $32
ENTITY_MONSTERBIRD_RIGHT        = $33
ENTITY_SMALL_FISH_RIGHT         = $34
ENTITY_KILLER_FISH_RIGHT        = $35
ENTITY_BAT_RIGHT                = $36
ENTITY_MONSTER_FROG_JUMPING     = $37
ENTITY_DEBRIS_TOP_LEFT          = $38
ENTITY_DEBRIS_BOTTOM_LEFT       = $39
ENTITY_DEBRIS_TOP_RIGHT         = $3A
ENTITY_DEBRIS_BOTTOM_RIGHT      = $3B
ENTITY_MONEY_BAG                = $3C
ENTITY_FLAME_OR_SCORPION_LEFT   = $3E
ENTITY_FLAME_OR_SCORPION_RIGHT  = $3F
ENTITY_RICE_BALL                = $44
ENTITY_SAINT_NURARI             = $45
ENTITY_NAMETABLE_CHANGER        = $4B
ENTITY_LIFE                     = $4D
ENTITY_POWER_BRACELET           = $4E
ENTITY_GHOST                    = $4F
ENTITY_ARROW                    = $56
ENTITY_JANKENS_CASTLE           = $58

; Entity config
LIFE_LIFESPAN                   = $F0
POWER_BRACELET_LIFESPAN         = $F0
MONEY_BAG_LIFESPAN              = $F0
GHOST_IDLE_TIME                 = $80

DEBRIS_GRAVITY                  = $0030