; Message indexes
TXT_PARPLIN             = $04
TXT_CHOKKINNA           = $05
TXT_GOOSEKA             = $06
TXT_BATTLE_ROUND_LOST   = $08
TXT_BATTLE_ROUND_WON    = $09
TXT_BATTLE_ROUND_TIE    = $0A
TXT_JANKEN              = $0C
TXT_BATTLE_LOST         = $15
