name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout WLA-DX
        uses: actions/checkout@v2
        with:
          path: wla-dx
          ref: v10.0
          repository: vhelin/wla-dx

      - name: Install WLA-DX
        working-directory: wla-dx
        run: |
          cmake -G "Unix Makefiles"
          make wla-z80 wlalink
          echo "$PWD/binaries" >> $GITHUB_PATH

      - name: Build and compare
        run: |
          ./compile.sh

